language: node_js
node_js:
  - "7"
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - docker

after_success:
  - codecov
  - >
    if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
        [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "This will deploy!"
    else
      echo "This will not deploy!"
    fi