---
swagger: "2.0"
info:
  description: "Provider Client Services"
  version: "1.0"
  title: "provider-client-services"
host: "localhost:8080"
basePath: "/"
schemes:
- "http"
paths:
  /health:
    get:
      summary: "Health check"
      description: ""
      operationId: "health"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /session/store/{sessionId}:
    get:
      summary: "Fetch a transaction"
      description: ""
      operationId: "get"
      produces:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "sessionId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
    put:
      summary: "Store a transaction"
      description: ""
      operationId: "put"
      consumes:
      - "application/json;charset=UTF-8"
      parameters:
      - name: "sessionId"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "string"
      responses:
        default:
          description: "successful operation"
  /ticket/store/{guid}:
    post:
      summary: "Store a ticket"
      description: ""
      operationId: "fetchAndStoreTicketFromUrl"
      parameters:
      - name: "guid"
        in: "path"
        required: true
        type: "string"
      - name: "async"
        in: "query"
        required: false
        type: "boolean"
      - name: "url"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /ticket/upload/{guid}:
    post:
      summary: "Upload a ticket"
      description: ""
      operationId: "storeFile"
      parameters:
      - name: "guid"
        in: "path"
        required: true
        type: "string"
      - name: "async"
        in: "query"
        required: false
        type: "boolean"
      - name: "file"
        in: "query"
        required: true
        type: "ref"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
